[[block]]
block = "net"
device = "enp0s20f0u2"
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}° max"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
format = " %a, %d %b     %I:%M"
timezone = "America/Denver"
interval = 60
